(() => {
  const all = Array.isArray(window.LIVESTREAMS) ? [...window.LIVESTREAMS].sort((a,b) => String(b.date).localeCompare(String(a.date)) || String(b.id).localeCompare(String(a.id))) : [];
  const $ = (s) => document.querySelector(s);
  const copy = {
    en:{brand:'THE BOYZ / FAN ARCHIVE',solid:'LIVESTREAMS',outline:'ARCHIVE',streams:'STREAMS',updated:'UPDATED',search:'SEARCH TITLES, MEMBERS...',filters:'FILTERS',year:'YEAR',member:'MEMBER',platform:'PLATFORM',allYears:'ALL YEARS',allMembers:'ALL MEMBERS',allPlatforms:'ALL PLATFORMS',allTab:'ALL',resultsAll:'ALL YEARS',stream:'STREAM',streamsResult:'STREAMS',membersLabel:'MEMBERS',platformLabel:'PLATFORM',watch:'WATCH →',copyLink:'COPY LINK',loadMore:'LOAD MORE ↓',noResults:'NO RESULTS',tryChange:'Try changing the search or filters.',mainArchive:'← MAIN ARCHIVE',backTop:'BACK TO TOP ↑',pageTitle:'Livestream Archive — THE BOYZ ARCHIVE',switchLabel:'Switch to Korean'},
    ko:{brand:'더보이즈 / 팬 아카이브',solid:'라이브스트림',outline:'아카이브',streams:'라이브',updated:'업데이트',search:'제목, 멤버 검색...',filters:'필터',year:'연도',member:'멤버',platform:'플랫폼',allYears:'전체 연도',allMembers:'전체 멤버',allPlatforms:'전체 플랫폼',allTab:'전체',resultsAll:'전체 연도',stream:'라이브',streamsResult:'라이브',membersLabel:'멤버',platformLabel:'플랫폼',watch:'보기 →',copyLink:'링크 복사',loadMore:'더 보기 ↓',noResults:'검색 결과 없음',tryChange:'검색어나 필터를 변경해 보세요.',mainArchive:'← 메인 아카이브',backTop:'맨 위로 ↑',pageTitle:'라이브스트림 아카이브 — 더보이즈 아카이브',switchLabel:'영어로 전환'}
  };
  let savedLanguage='en'; try{savedLanguage=localStorage.getItem('tbz-archive-language')==='ko'?'ko':'en'}catch{}
  const els={cards:$('#cards'),search:$('#search'),year:$('#yearFilter'),member:$('#memberFilter'),platform:$('#platformFilter'),tabs:$('#yearTabs'),label:$('#resultsLabel'),empty:$('#empty'),more:$('#loadMore'),grid:$('#gridView'),list:$('#listView'),filterRow:$('#filterRow'),filterToggle:$('#filtersToggle'),lang:$('#langToggle')};
  const latestYear=Math.max(...all.map(x=>Number(x.year)));
  let state={query:'',year:String(latestYear),member:'all',platform:'all',limit:24,view:'grid',lang:savedLanguage};
  const t=(key)=>copy[state.lang][key];
  const escapeHtml=(value='')=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const cleanMembers=(value='')=>String(value).split(',').map(x=>x.trim()).filter(Boolean);
  const years=[...new Set(all.map(x=>Number(x.year)))].sort((a,b)=>b-a);
  const memberOrder=['Sangyeon','Jacob','Younghoon','Hyunjae','Juyeon','Kevin','New','Q','Sunwoo','Eric'];
  const members=memberOrder.filter(name=>all.some(x=>cleanMembers(x.members).some(m=>m.toLowerCase()===name.toLowerCase())));
  const platforms=[...new Set(all.map(x=>x.platform).filter(x=>x&&x!=='Not specified'))].sort();
  const addOptions=(select,values)=>values.forEach(v=>select.insertAdjacentHTML('beforeend',`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`));
  addOptions(els.year,years); members.forEach(name=>els.member.insertAdjacentHTML('beforeend',`<option value="${escapeHtml(name)}">${name==='New'?'NEW':escapeHtml(name)}</option>`)); addOptions(els.platform,platforms); els.year.value=state.year;
  function buildTabs(){els.tabs.innerHTML=years.map(y=>`<button type="button" data-year="${y}" class="${String(y)===state.year?'selected':''}">${y}</button>`).join('')+`<button type="button" data-year="all">${t('allTab')}</button>`;}
  function updateStats(){const newest=all.map(x=>x.date).filter(Boolean).sort().at(-1);const updated=newest?new Date(newest+'T12:00:00').toLocaleDateString(state.lang==='ko'?'ko-KR':'en-US',{month:'short',year:'numeric'}).toUpperCase():String(latestYear);const stats=document.querySelectorAll('.stats p');stats[0].innerHTML=`<strong id="totalCount">${all.length.toLocaleString(state.lang==='ko'?'ko-KR':'en-US')}</strong> ${t('streams')}`;stats[1].innerHTML=`2017—<strong id="lastYear">${latestYear}</strong>`;stats[2].innerHTML=`${t('updated')} <strong id="updatedDate">${updated}</strong>`;}
  function filtered(){const q=state.query.toLocaleLowerCase();return all.filter(x=>{const matchesQ=!q||`${x.title} ${x.members}`.toLocaleLowerCase().includes(q);const matchesYear=state.year==='all'||String(x.year)===state.year;const matchesMember=state.member==='all'||cleanMembers(x.members).some(m=>m.toLowerCase()===state.member.toLowerCase())||/^all members$/i.test(x.members);const matchesPlatform=state.platform==='all'||x.platform===state.platform;return matchesQ&&matchesYear&&matchesMember&&matchesPlatform;});}
  function dateLabel(value){if(!value)return state.lang==='ko'?'날짜 미상':'DATE UNKNOWN';const d=new Date(value+'T12:00:00');return Number.isNaN(d.valueOf())?escapeHtml(value):d.toLocaleDateString(state.lang==='ko'?'ko-KR':'en-US',state.lang==='ko'?{year:'numeric',month:'long',day:'numeric'}:{month:'short',day:'2-digit',year:'numeric'}).toUpperCase();}
  function card(x){const watch=x.watch?`<a class="watch" href="${escapeHtml(x.watch)}" target="_blank" rel="noreferrer">${t('watch')}</a>`:`<span class="watch no-link">${t('watch')}</span>`;const image=x.thumbnail?`<img src="${escapeHtml(x.thumbnail)}" alt="" loading="lazy" decoding="async" onerror="this.remove()">`:'';return `<article class="card"><a class="thumb" ${x.watch?`href="${escapeHtml(x.watch)}" target="_blank" rel="noreferrer"`:''}>${image}</a><div class="card-info"><span class="date">${dateLabel(x.date)}</span><h2>${escapeHtml(x.title)}</h2><div class="meta"><span>${t('membersLabel')}</span><b>${escapeHtml(x.members)}</b><span>${t('platformLabel')}</span><b>${escapeHtml(x.platform)}</b></div><div class="actions">${watch}<button type="button" class="copy" data-link="${escapeHtml(x.watch||'')}">${t('copyLink')}</button></div></div></article>`;}
  function render(reset=true){if(reset)state.limit=24;const list=filtered();const shown=list.slice(0,state.limit);els.cards.innerHTML=shown.map(card).join('');els.empty.hidden=list.length!==0;els.more.hidden=shown.length>=list.length;els.label.textContent=`${state.year==='all'?t('resultsAll'):state.year} · ${list.length.toLocaleString(state.lang==='ko'?'ko-KR':'en-US')} ${list.length===1?t('stream'):t('streamsResult')}`;els.tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.year===state.year));els.year.value=state.year;}
  function applyLanguage(){document.documentElement.lang=state.lang==='ko'?'ko':'en';document.title=t('pageTitle');document.querySelector('.brand').textContent=t('brand');document.querySelector('.masthead h1 .solid').textContent=t('solid');document.querySelector('.masthead h1 .outline').textContent=t('outline');els.lang.textContent=state.lang==='ko'?'KOR':'EN';els.lang.setAttribute('aria-label',t('switchLabel'));els.search.placeholder=t('search');const labels=els.filterRow.querySelectorAll('label');labels[0].firstChild.nodeValue=t('year');labels[1].firstChild.nodeValue=t('member');labels[2].firstChild.nodeValue=t('platform');els.year.options[0].textContent=t('allYears');els.member.options[0].textContent=t('allMembers');els.platform.options[0].textContent=t('allPlatforms');els.filterToggle.innerHTML=`<span>☷</span> ${t('filters')} <b>${els.filterRow.classList.contains('closed')?'⌄':'⌃'}</b>`;els.more.textContent=t('loadMore');els.empty.querySelector('span').textContent=t('noResults');els.empty.querySelector('p').textContent=t('tryChange');const footer=document.querySelectorAll('footer a');footer[0].textContent=t('mainArchive');footer[1].textContent=t('backTop');updateStats();buildTabs();render(false);}
  let searchTimer;els.search.addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.query=e.target.value.trim();render();},120)});els.year.addEventListener('change',e=>{state.year=e.target.value;render()});els.member.addEventListener('change',e=>{state.member=e.target.value;render()});els.platform.addEventListener('change',e=>{state.platform=e.target.value;render()});els.tabs.addEventListener('click',e=>{const b=e.target.closest('button[data-year]');if(!b)return;state.year=b.dataset.year;render();});els.more.addEventListener('click',()=>{state.limit+=24;render(false)});els.cards.addEventListener('click',async e=>{const b=e.target.closest('.copy');if(!b)return;const link=b.dataset.link;if(!link)return;try{await navigator.clipboard.writeText(link);b.classList.add('done');setTimeout(()=>b.classList.remove('done'),1500)}catch{prompt(state.lang==='ko'?'이 링크를 복사하세요:':'Copy this link:',link)}});function setView(view){state.view=view;els.cards.classList.toggle('list-view',view==='list');els.grid.classList.toggle('selected',view==='grid');els.list.classList.toggle('selected',view==='list')}els.grid.addEventListener('click',()=>setView('grid'));els.list.addEventListener('click',()=>setView('list'));els.filterToggle.addEventListener('click',()=>{const closed=els.filterRow.classList.toggle('closed');els.filterToggle.setAttribute('aria-expanded',String(!closed));els.filterToggle.querySelector('b').textContent=closed?'⌄':'⌃'});els.lang.addEventListener('click',()=>{state.lang=state.lang==='en'?'ko':'en';try{localStorage.setItem('tbz-archive-language',state.lang)}catch{}applyLanguage()});applyLanguage();
})();
