"""Generate data/livestreams.js from an exported Livestreams workbook."""
import argparse,json,re
from datetime import date,datetime
from pathlib import Path
from urllib.parse import parse_qs,urlparse
from openpyxl import load_workbook

ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/"source"/"Livestreams.xlsx"
DESTINATION=ROOT/"data"/"livestreams.js"
TWITTER_HOSTS={"x.com","www.x.com","twitter.com","www.twitter.com","t.co","www.t.co"}

def normalized(value):return re.sub(r"[^a-z0-9]+"," ",str(value or "").lower()).strip()
def is_url(value):return isinstance(value,str) and re.match(r"^https?://",value.strip(),re.I)
def cell_url(cell):
 if cell.hyperlink and cell.hyperlink.target:return str(cell.hyperlink.target).strip()
 value=cell.value
 if is_url(value):return value.strip()
 if isinstance(value,str) and value.startswith("=HYPERLINK"):
  match=re.search(r'HYPERLINK\(\s*"([^"]+)"',value,re.I)
  if match:return match.group(1).replace('""','"')
 return ""
def is_twitter(url):
 try:return urlparse(url).netloc.lower() in TWITTER_HOSTS
 except ValueError:return False
def youtube_id(url):
 if not url:return ""
 try:
  parsed=urlparse(url);host=parsed.netloc.lower();path=parsed.path.strip("/")
  if host in {"youtu.be","www.youtu.be"}:candidate=path.split("/")[0]
  elif "youtube.com" in host or "youtube-nocookie.com" in host:
   if path=="watch":candidate=parse_qs(parsed.query).get("v",[""])[0]
   elif path.startswith(("shorts/","embed/","live/")):candidate=path.split("/")[1]
   else:candidate=""
  else:return ""
  return candidate if re.fullmatch(r"[A-Za-z0-9_-]{6,20}",candidate or "") else ""
 except (ValueError,IndexError):return ""
def iso_date(value,year):
 if isinstance(value,(datetime,date)):return value.strftime("%Y-%m-%d")
 text=str(value or "").strip()
 for pattern in (r"(\d{4})[-./](\d{1,2})[-./](\d{1,2})",r"(\d{1,2})[-./](\d{1,2})[-./](\d{4})"):
  match=re.search(pattern,text)
  if match:
   parts=list(map(int,match.groups()));y,m,d=(parts if len(str(parts[0]))==4 else (parts[2],parts[1],parts[0]))
   try:return date(y,m,d).isoformat()
   except ValueError:pass
 return f"{year}-01-01" if str(year).isdigit() else ""
def choose_watch(ws,row,headers,title_col):
 preferred=[];fallback=[]
 for col,header in headers.items():
  if "subtitle" in header or "english subs" in header or header=="thumbnail url":continue
  url=cell_url(ws.cell(row,col))
  if not url or is_twitter(url):continue
  if header=="watch url":preferred.insert(0,url)
  elif "backup" in header:preferred.append(url)
  elif col==title_col:fallback.append(url)
  else:fallback.append(url)
 return (preferred+fallback+[""])[0]
def build(source=SOURCE):
 workbook=load_workbook(source,data_only=False,read_only=False);items=[]
 for ws in workbook.worksheets:
  if not ws.title.isdigit():continue
  year=int(ws.title);headers={col:normalized(ws.cell(1,col).value) for col in range(1,ws.max_column+1)}
  by_name={name:col for col,name in headers.items() if name}
  title_col=by_name.get("title",1);members_col=by_name.get("members",3);date_col=by_name.get("post date",4)
  platform_col=by_name.get("platform") or (7 if ws.title in {"2017","2018","2024","2025","2026"} and ws.max_column>=7 else 5)
  thumbnail_col=by_name.get("thumbnail url") or by_name.get("thumbnail")
  sequence=0
  for row in range(2,ws.max_row+1):
   title=str(ws.cell(row,title_col).value or "").strip()
   if not title:continue
   sequence+=1;date_value=iso_date(ws.cell(row,date_col).value,year)
   members=str(ws.cell(row,members_col).value or "Not specified").strip();platform=str(ws.cell(row,platform_col).value or "Not specified").strip()
   if title.casefold()=="jacob birthday tiktok live" and date_value=="2026-05-31":platform="Tiktok"
   watch=choose_watch(ws,row,headers,title_col)
   thumbnail=cell_url(ws.cell(row,thumbnail_col)) if thumbnail_col else ""
   if not thumbnail:
    video_id=youtube_id(watch)
    if video_id:thumbnail=f"https://i.ytimg.com/vi/{video_id}/hqdefault.jpg"
   items.append({"id":f"{year}-{sequence:03d}","title":title,"members":members,"date":date_value,"year":year,"platform":platform,"watch":watch,"thumbnail":thumbnail})
 items.sort(key=lambda item:(item["date"],item["id"]),reverse=True)
 payload=json.dumps(items,ensure_ascii=False,indent=2).replace("<","\\u003c").replace(">","\\u003e").replace("&","\\u0026")
 DESTINATION.parent.mkdir(parents=True,exist_ok=True)
 DESTINATION.write_text('// Generated automatically from the public Google Sheets archive. Do not edit this file manually.\nwindow.LIVESTREAMS = '+payload+';\n',encoding="utf-8")
 print(f"Wrote {len(items)} livestreams to {DESTINATION.relative_to(ROOT)}")
if __name__=="__main__":
 parser=argparse.ArgumentParser();parser.add_argument("--source",type=Path,default=SOURCE)
 args=parser.parse_args();build(args.source)



